### ISSUE TITLE
score de muchas clacias

### ISSUE THREAD

**Issue by FFlabanquise** [Labanquise/muchas-glacias#15]
![image](https://user-images.githubusercontent.com/78426786/110292773-02bfcb80-7fee-11eb-8b1c-da10f59dca8d.png)

81 en accessiblité
93 en best practices
85 en seo

**Comment by Frackher** [comment]
![image](https://user-images.githubusercontent.com/265578/110307437-2f301380-7fff-11eb-8fae-713961e9a826.png)
